I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 200, in script
    if tutorial.move_after:
  File "game/script.rpy", line 200, in <module>
    if tutorial.move_after:
AttributeError: 'bool' object has no attribute 'move_after'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 200, in script
    if tutorial.move_after:
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 1832, in execute
    if renpy.python.py_eval(condition):
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2059, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2052, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 200, in <module>
    if tutorial.move_after:
AttributeError: 'bool' object has no attribute 'move_after'

Darwin-19.6.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Gates of Galloo 1.0
Mon Nov 23 22:16:34 2020
